"""
🔍 Agent 2: Recurrent Pattern Detector (Pₖ-scanner)

This agent detects repeated or self-similar configurations within the binary
sequence Φ generated by Level 0, identifying patterns Pₖ(Φ) that constitute
the basis of the Primordial Holographic Field.

Version v33: Now supports structural pattern detection (parentheses analysis)
for emergent order detection.

Version v34: Added RAM-aware parallel processing to prevent resource exhaustion.

Autor: Iban Borràs amb col·laboració d'Augment Agent
Data: Gener 2025
"""

import os
import numpy as np
import json
from typing import List, Dict, Any, Tuple, Optional
from pathlib import Path
from collections import defaultdict, Counter
import hashlib
from scipy import signal
from sklearn.cluster import DBSCAN
from concurrent.futures import ProcessPoolExecutor, as_completed

# RAM monitoring for adaptive parallelism
try:
    import psutil
    HAS_PSUTIL = True
except ImportError:
    HAS_PSUTIL = False

# Import structural pattern detector
try:
    from .structural_pattern_detector import StructuralPatternDetector
    STRUCTURAL_AVAILABLE = True
except ImportError:
    STRUCTURAL_AVAILABLE = False

# Import Numba-optimized kernels
try:
    from .numba_kernels import (
        str_to_bytes, bytes_to_str, sliding_window_hashes,
        block_similarities, compute_autosimilarity
    )
    NUMBA_AVAILABLE = True
    print("✅ Numba acceleration enabled")
except ImportError:
    NUMBA_AVAILABLE = False
    print("⚠️ Numba not available, using pure Python (slower)")


# =============================================================================
# RAM-AWARE PARALLEL PROCESSING HELPERS
# =============================================================================

def _get_adaptive_workers(base_workers: int, ram_threshold: float = 75.0,
                          min_workers: int = 2, verbose: bool = False) -> int:
    """
    Dynamically reduce workers based on RAM pressure.
    More aggressive reduction: halves workers for every 10% above threshold.
    """
    if not HAS_PSUTIL:
        return base_workers

    ram_percent = psutil.virtual_memory().percent

    if ram_percent < ram_threshold:
        return base_workers

    # Aggressive reduction: halve for every 10% above threshold
    reduction_steps = int((ram_percent - ram_threshold) / 10) + 1
    new_workers = max(min_workers, base_workers // (2 ** reduction_steps))

    if verbose and new_workers < base_workers:
        print(f"   ⚠️ RAM at {ram_percent:.1f}% - reducing workers: {base_workers} → {new_workers}", flush=True)

    return new_workers


def _wait_for_ram(target_percent: float = 70.0, max_wait: int = 120,
                  check_interval: int = 5, verbose: bool = False) -> bool:
    """
    Wait until RAM usage drops below target percentage.
    """
    if not HAS_PSUTIL:
        return True  # Can't check, assume OK

    import time
    waited = 0
    initial_ram = psutil.virtual_memory().percent

    if initial_ram <= target_percent:
        return True

    if verbose:
        print(f"   ⏳ RAM at {initial_ram:.1f}% - waiting for <{target_percent}%...", flush=True)

    while waited < max_wait:
        time.sleep(check_interval)
        waited += check_interval
        current_ram = psutil.virtual_memory().percent

        if current_ram <= target_percent:
            if verbose:
                print(f"   ✅ RAM dropped to {current_ram:.1f}% after {waited}s", flush=True)
            return True

    if verbose:
        print(f"   ⚠️ RAM still at {psutil.virtual_memory().percent:.1f}% after {max_wait}s timeout", flush=True)
    return False


# =============================================================================
# PARALLEL CHUNK PROCESSING HELPER (module-level for pickling)
# =============================================================================

def _process_pattern_chunk(args: tuple) -> dict:
    """
    Process a single chunk for pattern detection.
    Must be at module level for multiprocessing.

    Args:
        args: (chunk_str, chunk_idx, start_offset, min_len, max_len, overlap, is_first_chunk)

    Returns:
        dict with patterns found in this chunk
    """
    chunk, chunk_idx, start_offset, min_len, max_len, overlap, is_first = args

    if not NUMBA_AVAILABLE:
        return {'chunk_idx': chunk_idx, 'patterns': {}}

    chunk_bytes = str_to_bytes(chunk)

    # Get hashes for this chunk
    hashes, starts, lengths = sliding_window_hashes(chunk_bytes, min_len, max_len)

    # Aggregate patterns from this chunk
    chunk_patterns = {}  # hash -> {'pattern': str, 'count': int, 'positions': list}
    MAX_POSITIONS = 100  # Fewer positions per chunk to save memory

    for i in range(len(hashes)):
        h = int(hashes[i])
        pos = int(starts[i])
        length = int(lengths[i])

        # Avoid counting patterns in overlap region twice (except first chunk)
        if not is_first and pos < overlap:
            continue

        global_pos = start_offset + pos

        if h in chunk_patterns:
            chunk_patterns[h]['count'] += 1
            if len(chunk_patterns[h]['positions']) < MAX_POSITIONS:
                chunk_patterns[h]['positions'].append(global_pos)
        else:
            chunk_patterns[h] = {
                'pattern': chunk[pos:pos + length],
                'count': 1,
                'positions': [global_pos]
            }

    return {'chunk_idx': chunk_idx, 'patterns': chunk_patterns}


def _load_pattern_config() -> Dict[str, Any]:
    """Load pattern detection thresholds from config.json if available."""
    config_path = Path(__file__).parent.parent / 'config.json'
    defaults = {
        'large_sequence_threshold': 10_000_000,  # 10M bits
        'sample_size': 1_000_000  # 1M bits
    }
    try:
        if config_path.exists():
            with open(config_path) as f:
                config = json.load(f)
            pd_config = config.get('pattern_detection', {})
            return {
                'large_sequence_threshold': pd_config.get('large_sequence_threshold', defaults['large_sequence_threshold']),
                'sample_size': pd_config.get('sample_size', defaults['sample_size'])
            }
    except Exception:
        pass
    return defaults


class PatternDetector:
    """
    Agent for detecting recurrent patterns Pₖ in binary sequences Φ.

    Uses multiple methods to identify regularities:
    - Sliding windows with hashing
    - Block segmentation and similarity comparison
    - Local spectral analysis
    - Self-similarity detection
    """

    def __init__(self,
                 min_pattern_length: int = 3,
                 max_pattern_length: int = 50,
                 min_occurrences: int = 2,
                 similarity_threshold: float = 0.8,
                 enable_structural_analysis: bool = True,
                 large_sequence_threshold: Optional[int] = None,
                 sample_size: Optional[int] = None):
        """
        Initialize the pattern detector.

        Args:
            min_pattern_length: Minimum length of patterns to detect
            max_pattern_length: Maximum length of patterns to detect
            min_occurrences: Minimum occurrences to consider a pattern
            similarity_threshold: Similarity threshold for grouping patterns
            enable_structural_analysis: Enable v33 structural pattern detection
            large_sequence_threshold: Sequences above this size trigger sampling mode.
                                      If None, loads from config.json (default: 10M bits)
            sample_size: When in sampling mode, analyze this many bits per sample.
                         If None, loads from config.json (default: 1M bits)
        """
        self.min_pattern_length = min_pattern_length
        self.max_pattern_length = max_pattern_length
        self.min_occurrences = min_occurrences
        self.similarity_threshold = similarity_threshold
        self.enable_structural_analysis = enable_structural_analysis

        # Load thresholds from config if not provided
        config = _load_pattern_config()
        self.large_sequence_threshold = large_sequence_threshold or config['large_sequence_threshold']
        self.sample_size = sample_size or config['sample_size']

        self.detected_patterns = []
        self.structural_patterns = []
        self.pattern_stats = {}

        # Initialize structural detector if available
        if self.enable_structural_analysis and STRUCTURAL_AVAILABLE:
            self.structural_detector = StructuralPatternDetector(
                min_depth=1,
                max_depth=50,
                min_occurrences=min_occurrences
            )
        else:
            self.structural_detector = None
    
    def detect_patterns(self, phi_sequence: str, phi_structural: Optional[str] = None) -> List[Dict[str, Any]]:
        """
        Detecta patrons en la seqüència Φ utilitzant múltiples mètodes.

        Args:
            phi_sequence: Seqüència binària Φ com a string (observable, sense parentheses)
            phi_structural: Optional structural Φ with parentheses (v33 format)

        Returns:
            Llista de patrons detectats amb les seves mètriques
        """
        seq_len = len(phi_sequence)
        print(f"🔍 Detecting patterns in sequence of length {seq_len:,}")

        # Use configurable thresholds (from config.json or constructor)
        is_large = seq_len > self.large_sequence_threshold

        # Method 1: Sliding windows with hashing (works with chunking for large seqs)
        sliding_patterns = self._detect_sliding_window_patterns(phi_sequence)
        print(f"   ✓ Sliding window: {len(sliding_patterns):,} patterns", flush=True)

        block_patterns = []
        spectral_patterns = []

        if is_large:
            # For large sequences, use sampling for block/spectral analysis
            sample_size = self.sample_size
            print(f"   ⏳ Block patterns (sampling mode: {sample_size:,} bits)...", flush=True)
            sample_start = seq_len // 2 - sample_size // 2  # Middle sample
            sample = phi_sequence[sample_start:sample_start + sample_size]
            phi_array_sample = np.array([int(bit) for bit in sample], dtype=np.uint8)
            block_patterns = self._detect_block_patterns(phi_array_sample)
            # Adjust positions to global coordinates
            for p in block_patterns:
                p['positions'] = [pos + sample_start for pos in p['positions']]
            print(f"   ✓ Block patterns: {len(block_patterns):,} patterns (from {sample_size:,} sample)", flush=True)

            print(f"   ⏳ Spectral analysis (sampling mode)...", flush=True)
            spectral_patterns = self._detect_spectral_patterns(phi_array_sample)
            for p in spectral_patterns:
                if 'positions' in p:
                    p['positions'] = [pos + sample_start for pos in p['positions']]
            print(f"   ✓ Spectral patterns: {len(spectral_patterns):,} patterns (from {sample_size:,} sample)", flush=True)

            del phi_array_sample  # Free memory
        else:
            # For normal sequences, use full analysis
            phi_array = np.array([int(bit) for bit in phi_sequence], dtype=np.uint8)

            print(f"   ⏳ Block patterns...", flush=True)
            block_patterns = self._detect_block_patterns(phi_array)
            print(f"   ✓ Block patterns: {len(block_patterns):,} patterns", flush=True)

            print(f"   ⏳ Spectral analysis...", flush=True)
            spectral_patterns = self._detect_spectral_patterns(phi_array)
            print(f"   ✓ Spectral patterns: {len(spectral_patterns):,} patterns", flush=True)

            del phi_array  # Free memory

        # Combine and filter patterns
        all_patterns = sliding_patterns + block_patterns + spectral_patterns
        print(f"   ⏳ Filtering & merging {len(all_patterns):,} patterns...", flush=True)
        filtered_patterns = self._filter_and_merge_patterns(all_patterns, phi_sequence)
        print(f"   ✓ After filtering: {len(filtered_patterns):,} patterns", flush=True)

        # Limit patterns for very large sequences to avoid excessive computation
        MAX_PATTERNS_FOR_METRICS = 50_000
        if len(filtered_patterns) > MAX_PATTERNS_FOR_METRICS:
            print(f"   ⚠️ Limiting to top {MAX_PATTERNS_FOR_METRICS:,} patterns by recurrence for metrics calculation")
            # Sort by recurrence and keep top patterns
            filtered_patterns = sorted(filtered_patterns, key=lambda p: p.get('recurrence', 0), reverse=True)
            filtered_patterns = filtered_patterns[:MAX_PATTERNS_FOR_METRICS]

        # Calculate detailed metrics for each pattern
        print(f"   ⏳ Calculating metrics for {len(filtered_patterns):,} patterns...", flush=True)
        enriched_patterns = []
        total = len(filtered_patterns)
        for idx, pattern in enumerate(filtered_patterns):
            if idx > 0 and idx % 5000 == 0:
                print(f"   [metrics] {idx:,}/{total:,} ({100*idx//total}%)", flush=True)
            enriched_pattern = self._calculate_pattern_metrics(pattern, phi_sequence)
            enriched_patterns.append(enriched_pattern)

        self.detected_patterns = enriched_patterns

        # Detect structural patterns if available
        if phi_structural and self.structural_detector:
            print(f"🔍 Detecting structural patterns (v33)...")
            self.structural_patterns = self.structural_detector.detect_structural_patterns(phi_structural)
            print(f"   ✅ {len(self.structural_patterns)} structural patterns detected")

        return enriched_patterns

    def get_structural_patterns(self) -> List[Dict[str, Any]]:
        """
        Get detected structural patterns (v33 only).

        Returns:
            List of structural patterns, or empty list if not available
        """
        return self.structural_patterns if hasattr(self, 'structural_patterns') else []
    
    def _detect_sliding_window_patterns(self, sequence: str) -> List[Dict[str, Any]]:
        """Detect patterns using sliding windows with hashing."""
        patterns = []
        seq_len = len(sequence)
        max_len = min(self.max_pattern_length, seq_len // 4)

        if NUMBA_AVAILABLE and seq_len > 10000:
            # Use Numba-optimized version for large sequences
            return self._detect_sliding_window_numba(sequence, max_len)

        # Fallback to pure Python
        pattern_counts = defaultdict(list)

        # For large sequences, use sampling to reduce computation
        step = 1
        if seq_len > 50000:
            step = 2  # Sample every 2nd position for large sequences
            print(f"   [sliding] Using step={step} for large sequence ({seq_len:,} chars)")

        total_lengths = max_len - self.min_pattern_length

        # Try different pattern lengths
        for idx, length in enumerate(range(self.min_pattern_length, max_len)):
            if idx % 5 == 0:  # Progress every 5 lengths
                print(f"   [sliding] Length {length}/{max_len} ({100*idx//total_lengths}%)", end='\r')

            # Sliding window with optional sampling
            for i in range(0, seq_len - length + 1, step):
                pattern = sequence[i:i + length]
                pattern_counts[pattern].append(i)

        print(f"   [sliding] Done. Filtering {len(pattern_counts):,} unique patterns...")

        # Filter patterns with enough occurrences
        for pattern, positions in pattern_counts.items():
            if len(positions) >= self.min_occurrences:
                patterns.append({
                    'pattern_id': f'sw_{hashlib.md5(pattern.encode()).hexdigest()[:8]}',
                    'pattern_data': pattern,
                    'positions': positions,
                    'method': 'sliding_window',
                    'recurrence': len(positions)
                })

        return patterns

    def _detect_sliding_window_numba(self, sequence: str, max_len: int,
                                      max_cpu_percent: int = 50) -> List[Dict[str, Any]]:
        """
        Numba-optimized sliding window pattern detection with PARALLEL chunking.

        Args:
            sequence: Binary sequence string
            max_len: Maximum pattern length
            max_cpu_percent: Maximum CPU usage (default 50%)
        """
        seq_len = len(sequence)

        # For very large sequences, limit max pattern length to reduce memory
        if seq_len > 100_000_000:  # 100M+ chars
            max_len = min(max_len, 15)  # Max 15 chars for huge sequences
            print(f"   [sliding] Limiting max_len to {max_len} for memory efficiency")
        elif seq_len > 10_000_000:  # 10M+ chars
            max_len = min(max_len, 20)  # Max 20 chars for large sequences

        # Chunk size: 5M chars (reduced for memory safety)
        CHUNK_SIZE = 5_000_000
        OVERLAP = max_len  # Overlap to catch patterns at boundaries

        # For small sequences, use direct processing
        if seq_len <= CHUNK_SIZE:
            return self._detect_sliding_window_numba_direct(sequence, max_len)

        # Parallel chunked processing for large sequences with RAM-aware batching
        total_cores = os.cpu_count() or 4
        base_workers = max(1, int(total_cores * max_cpu_percent / 100))

        print(f"   [sliding] Using Numba + PARALLEL (up to {base_workers} workers, RAM-adaptive)")
        print(f"   [sliding] seq={seq_len:,}, chunk={CHUNK_SIZE:,}...")

        num_chunks = (seq_len + CHUNK_SIZE - 1) // CHUNK_SIZE

        # Prepare chunk arguments
        chunk_args = []
        for chunk_idx in range(num_chunks):
            start = chunk_idx * CHUNK_SIZE
            end = min(start + CHUNK_SIZE + OVERLAP, seq_len)
            chunk = sequence[start:end]
            is_first = (chunk_idx == 0)
            chunk_args.append((chunk, chunk_idx, start, self.min_pattern_length,
                              max_len, OVERLAP, is_first))

        # Process chunks in batches with pool recreation (prevents resource exhaustion)
        global_patterns = {}  # hash -> {'pattern': str, 'count': int, 'positions': list}
        MAX_POSITIONS_PER_PATTERN = 1000
        completed = 0
        failed_chunks = []
        BATCH_SIZE = 50  # Process 50 chunks per batch, then recreate pool
        MAX_RETRIES = 2

        for batch_start in range(0, num_chunks, BATCH_SIZE):
            batch_end = min(batch_start + BATCH_SIZE, num_chunks)
            batch_args = chunk_args[batch_start:batch_end]

            # Adaptive worker count based on RAM
            n_workers = _get_adaptive_workers(base_workers, ram_threshold=75.0,
                                               min_workers=2, verbose=True)

            # Wait for RAM if needed before starting batch
            _wait_for_ram(target_percent=70.0, max_wait=60, verbose=True)

            batch_failed = []

            with ProcessPoolExecutor(max_workers=n_workers) as executor:
                futures = {executor.submit(_process_pattern_chunk, args): args[1]
                          for args in batch_args}

                for future in as_completed(futures):
                    completed += 1
                    chunk_idx = futures[future]
                    try:
                        result = future.result(timeout=300)  # 5 min timeout
                        chunk_patterns = result['patterns']

                        # Merge into global patterns
                        for h, data in chunk_patterns.items():
                            if h in global_patterns:
                                global_patterns[h]['count'] += data['count']
                                remaining = MAX_POSITIONS_PER_PATTERN - len(global_patterns[h]['positions'])
                                if remaining > 0:
                                    global_patterns[h]['positions'].extend(data['positions'][:remaining])
                            else:
                                global_patterns[h] = data

                    except Exception as e:
                        error_msg = str(e)
                        if 'handle is closed' in error_msg or 'BrokenProcessPool' in error_msg:
                            batch_failed.append(batch_args[chunk_idx - batch_start])
                        print(f"   [sliding] Chunk {chunk_idx} error: {error_msg[:80]}", flush=True)

            # Retry failed chunks sequentially
            if batch_failed:
                print(f"   [sliding] Retrying {len(batch_failed)} failed chunks...", flush=True)
                _wait_for_ram(target_percent=70.0, max_wait=120, verbose=True)

                for args in batch_failed:
                    for retry in range(MAX_RETRIES):
                        try:
                            result = _process_pattern_chunk(args)
                            chunk_patterns = result['patterns']
                            for h, data in chunk_patterns.items():
                                if h in global_patterns:
                                    global_patterns[h]['count'] += data['count']
                                else:
                                    global_patterns[h] = data
                            break
                        except Exception as e:
                            if retry == MAX_RETRIES - 1:
                                failed_chunks.append(args[1])
                                print(f"   [sliding] Chunk {args[1]} failed permanently", flush=True)

            # Progress log
            pct = completed / num_chunks * 100
            print(f"   [sliding] Progress: {completed}/{num_chunks} ({pct:.0f}%), "
                  f"{len(global_patterns):,} unique patterns", flush=True)

        if failed_chunks:
            print(f"   [sliding] ⚠️ {len(failed_chunks)} chunks failed permanently", flush=True)

        # Filter patterns with enough occurrences
        print(f"   [sliding] Filtering {len(global_patterns):,} unique patterns...")
        patterns = []
        for h, data in global_patterns.items():
            if data['count'] >= self.min_occurrences:
                pattern_str = data['pattern']
                patterns.append({
                    'pattern_id': f'sw_{hashlib.md5(pattern_str.encode()).hexdigest()[:8]}',
                    'pattern_data': pattern_str,
                    'positions': data['positions'],
                    'method': 'sliding_window_numba_parallel',
                    'recurrence': data['count']
                })

        print(f"   [sliding] Done. {len(patterns):,} patterns after filtering.")
        return patterns

    def _detect_sliding_window_numba_direct(self, sequence: str, max_len: int) -> List[Dict[str, Any]]:
        """Direct Numba sliding window for small sequences (no chunking)."""
        print(f"   [sliding] Using Numba acceleration (direct)...")

        seq_bytes = str_to_bytes(sequence)

        # Get all pattern hashes using Numba
        hashes, starts, lengths = sliding_window_hashes(
            seq_bytes, self.min_pattern_length, max_len
        )

        print(f"   [sliding] Computed {len(hashes):,} hashes, grouping...")

        # Group by hash (done in Python as dict operations)
        hash_to_positions = defaultdict(list)
        hash_to_pattern = {}

        for i in range(len(hashes)):
            h = hashes[i]
            pos = starts[i]
            length = lengths[i]
            hash_to_positions[h].append(pos)
            if h not in hash_to_pattern:
                hash_to_pattern[h] = sequence[pos:pos+length]

        print(f"   [sliding] Found {len(hash_to_positions):,} unique patterns, filtering...")

        # Filter patterns with enough occurrences
        patterns = []
        for h, positions in hash_to_positions.items():
            if len(positions) >= self.min_occurrences:
                pattern_str = hash_to_pattern[h]
                patterns.append({
                    'pattern_id': f'sw_{hashlib.md5(pattern_str.encode()).hexdigest()[:8]}',
                    'pattern_data': pattern_str,
                    'positions': positions,
                    'method': 'sliding_window_numba',
                    'recurrence': len(positions)
                })

        print(f"   [sliding] Done. {len(patterns):,} patterns after filtering.")
        return patterns
    
    def _detect_block_patterns(self, phi_array: np.ndarray) -> List[Dict[str, Any]]:
        """Detect patterns by segmenting sequence into blocks and comparing similarities."""
        patterns = []

        min_bs = self.min_pattern_length
        max_bs = min(self.max_pattern_length, len(phi_array) // 8)
        total_sizes = max(1, max_bs - min_bs)

        # Limit max blocks to avoid memory explosion (similarity matrix is n^2)
        MAX_BLOCKS = 5000  # 5000x5000 = 25M floats = ~200MB

        # Provar diferents mides de bloc
        for idx, block_size in enumerate(range(min_bs, max_bs)):
            if idx > 0 and idx % 10 == 0:
                print(f"      [block] size {block_size}/{max_bs} ({100*idx//total_sizes}%)", end='\r', flush=True)

            blocks = []
            positions = []

            # Calculate step to limit number of blocks
            min_step = block_size // 2
            total_possible = len(phi_array) // min_step
            step = max(min_step, len(phi_array) // MAX_BLOCKS) if total_possible > MAX_BLOCKS else min_step

            # Dividir en blocs
            for i in range(0, len(phi_array) - block_size + 1, step):
                block = phi_array[i:i + block_size]
                if len(block) == block_size:
                    blocks.append(block)
                    positions.append(i)
                    if len(blocks) >= MAX_BLOCKS:
                        break

            if len(blocks) < 2:
                continue

            # Agrupar blocs similars utilitzant clustering
            similarities = self._calculate_block_similarities(blocks)
            
            if len(similarities) > 0:
                # Utilitzar DBSCAN per agrupar blocs similars
                clustering = DBSCAN(eps=1-self.similarity_threshold, 
                                  min_samples=self.min_occurrences,
                                  metric='precomputed')
                
                distance_matrix = 1 - similarities
                labels = clustering.fit_predict(distance_matrix)
                
                # Create patterns for each cluster
                for cluster_id in set(labels):
                    if cluster_id != -1:  # Ignore noise
                        cluster_indices = np.where(labels == cluster_id)[0]
                        if len(cluster_indices) >= self.min_occurrences:
                            representative_block = blocks[cluster_indices[0]]
                            cluster_positions = [positions[i] for i in cluster_indices]
                            
                            pattern_data = ''.join(map(str, representative_block))
                            patterns.append({
                                'pattern_id': f'bl_{hashlib.md5(pattern_data.encode()).hexdigest()[:8]}',
                                'pattern_data': pattern_data,
                                'positions': cluster_positions,
                                'method': 'block_clustering',
                                'recurrence': len(cluster_positions)
                            })
        
        return patterns
    
    def _detect_spectral_patterns(self, phi_array: np.ndarray) -> List[Dict[str, Any]]:
        """Detect patterns using spectral analysis (FFT)."""
        patterns = []

        # For very large arrays, subsample for FFT
        MAX_FFT_SIZE = 100_000  # 100k points max for FFT
        if len(phi_array) > MAX_FFT_SIZE:
            step = len(phi_array) // MAX_FFT_SIZE
            phi_array = phi_array[::step]

        if len(phi_array) < 64:  # Too short for spectral analysis
            return patterns

        # Calculate FFT of the sequence
        fft_result = np.fft.fft(phi_array.astype(float))
        power_spectrum = np.abs(fft_result) ** 2

        # Find significant peaks in power spectrum
        peaks, properties = signal.find_peaks(power_spectrum,
                                            height=np.mean(power_spectrum) * 2,
                                            distance=5)

        # Limit number of peaks to analyze
        MAX_PEAKS = 50
        if len(peaks) > MAX_PEAKS:
            # Keep only the strongest peaks
            peak_heights = power_spectrum[peaks]
            top_indices = np.argsort(peak_heights)[-MAX_PEAKS:]
            peaks = peaks[top_indices]

        # For each peak, try to identify the corresponding pattern
        for peak_idx in peaks:
            frequency = peak_idx / len(phi_array)
            if frequency > 0 and frequency < 0.5:  # Avoid frequency 0 and Nyquist
                period = int(1 / frequency)

                if self.min_pattern_length <= period <= self.max_pattern_length:
                    # Search for patterns with this periodicity
                    pattern_candidates = self._extract_periodic_patterns(phi_array, period)
                    patterns.extend(pattern_candidates)

        return patterns

    def _extract_periodic_patterns(self, phi_array: np.ndarray, period: int) -> List[Dict[str, Any]]:
        """Extract patterns with a specific periodicity."""
        patterns = []

        # Divide sequence into segments of period length
        segments = []
        positions = []
        
        for i in range(0, len(phi_array) - period + 1, period):
            segment = phi_array[i:i + period]
            if len(segment) == period:
                segments.append(segment)
                positions.append(i)
        
        if len(segments) < self.min_occurrences:
            return patterns
        
        # Find the most common segment
        segment_strings = [''.join(map(str, seg)) for seg in segments]
        segment_counts = Counter(segment_strings)

        for pattern_data, count in segment_counts.items():
            if count >= self.min_occurrences:
                # Find all positions of this pattern
                pattern_positions = []
                for i, seg_str in enumerate(segment_strings):
                    if seg_str == pattern_data:
                        pattern_positions.append(positions[i])
                
                patterns.append({
                    'pattern_id': f'sp_{hashlib.md5(pattern_data.encode()).hexdigest()[:8]}',
                    'pattern_data': pattern_data,
                    'positions': pattern_positions,
                    'method': 'spectral_periodic',
                    'recurrence': count,
                    'period': period
                })
        
        return patterns
    
    def _calculate_block_similarities(self, blocks: List[np.ndarray]) -> np.ndarray:
        """Calculate the similarity matrix between blocks."""
        n_blocks = len(blocks)

        # Use Numba if available and enough blocks
        if NUMBA_AVAILABLE and n_blocks > 10:
            # Convert list to 2D numpy array
            block_size = len(blocks[0])
            blocks_array = np.zeros((n_blocks, block_size), dtype=np.uint8)
            for i, block in enumerate(blocks):
                blocks_array[i] = block.astype(np.uint8)
            return block_similarities(blocks_array)

        # Fallback to pure Python
        similarities = np.zeros((n_blocks, n_blocks))

        for i in range(n_blocks):
            for j in range(i, n_blocks):
                if i == j:
                    similarities[i, j] = 1.0
                else:
                    # Calculate similarity as normalized correlation
                    correlation = np.corrcoef(blocks[i], blocks[j])[0, 1]
                    if np.isnan(correlation):
                        correlation = 0.0
                    similarities[i, j] = similarities[j, i] = max(0, correlation)

        return similarities
    
    def _filter_and_merge_patterns(self, patterns: List[Dict[str, Any]],
                                 sequence: str) -> List[Dict[str, Any]]:
        """Filter and merge similar or redundant patterns."""
        if not patterns:
            return []

        # Sort by recurrence (most frequent first)
        patterns.sort(key=lambda p: p['recurrence'], reverse=True)

        # Remove exact duplicates
        unique_patterns = []
        seen_patterns = set()

        for pattern in patterns:
            pattern_key = pattern['pattern_data']
            if pattern_key not in seen_patterns:
                seen_patterns.add(pattern_key)
                unique_patterns.append(pattern)

        # Filter patterns too short or with few occurrences
        filtered_patterns = [
            p for p in unique_patterns
            if len(p['pattern_data']) >= self.min_pattern_length
            and p['recurrence'] >= self.min_occurrences
        ]

        return filtered_patterns

    def _calculate_pattern_metrics(self, pattern: Dict[str, Any],
                                 sequence: str) -> Dict[str, Any]:
        """Calculate detailed metrics for a pattern."""
        pattern_data = pattern['pattern_data']
        positions = pattern['positions']

        # Density: proportion of sequence covered by pattern
        total_coverage = len(positions) * len(pattern_data)
        density = total_coverage / len(sequence)
        
        # Compressibilitat local
        compressibility = self._calculate_compressibility(pattern_data)
        
        # Autosimilarity
        autosimilarity = self._calculate_autosimilarity(pattern_data)

        # Spectral signature
        spectral_signature = self._calculate_spectral_signature(pattern_data)

        # Enrich pattern with new metrics
        enriched_pattern = pattern.copy()
        enriched_pattern.update({
            'density': density,
            'compressibility': compressibility,
            'autosimilarity': autosimilarity,
            'spectral_signature': spectral_signature.tolist() if spectral_signature is not None else None
        })
        
        return enriched_pattern
    
    def _calculate_compressibility(self, pattern_data: str) -> float:
        """Calcula la compressibilitat d'un patró."""
        import gzip
        
        original_size = len(pattern_data)
        if original_size == 0:
            return 0.0
        
        compressed_size = len(gzip.compress(pattern_data.encode()))
        compressibility = 1.0 - (compressed_size / original_size)
        
        return max(0.0, compressibility)
    
    def _calculate_autosimilarity(self, pattern_data: str) -> float:
        """Calcula l'autosimilitud d'un patró."""
        if len(pattern_data) < 4:
            return 0.0
        
        pattern_array = np.array([int(bit) for bit in pattern_data])
        
        # Calcular autocorrelació
        autocorr = np.correlate(pattern_array, pattern_array, mode='full')
        autocorr = autocorr[autocorr.size // 2:]
        
        # Normalitzar
        autocorr = autocorr / autocorr[0] if autocorr[0] != 0 else autocorr
        
        # Retornar la mitjana de l'autocorrelació (excloent el pic central)
        if len(autocorr) > 1:
            return np.mean(np.abs(autocorr[1:]))
        else:
            return 0.0
    
    def _calculate_spectral_signature(self, pattern_data: str) -> Optional[np.ndarray]:
        """Calcula la signatura espectral d'un patró."""
        if len(pattern_data) < 8:
            return None
        
        pattern_array = np.array([int(bit) for bit in pattern_data], dtype=float)
        
        # Calcular FFT
        fft_result = np.fft.fft(pattern_array)
        power_spectrum = np.abs(fft_result) ** 2
        
        # Normalize
        if np.sum(power_spectrum) > 0:
            power_spectrum = power_spectrum / np.sum(power_spectrum)

        # Return only first half (positive frequencies)
        return power_spectrum[:len(power_spectrum) // 2]

    def save_patterns(self, output_path: str) -> None:
        """Save detected patterns in JSON format."""
        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)

        with open(output_file, 'w') as f:
            json.dump(self.detected_patterns, f, indent=2)

        print(f"💾 Patterns saved to {output_path}")

    def get_pattern_summary(self) -> Dict[str, Any]:
        """Return a summary of detected patterns."""
        if not self.detected_patterns:
            return {"total_patterns": 0}

        total_patterns = len(self.detected_patterns)
        avg_length = np.mean([len(p['pattern_data']) for p in self.detected_patterns])
        avg_recurrence = np.mean([p['recurrence'] for p in self.detected_patterns])
        avg_density = np.mean([p.get('density', 0) for p in self.detected_patterns])

        methods_used = set(p.get('method', 'unknown') for p in self.detected_patterns)

        return {
            "total_patterns": total_patterns,
            "average_length": avg_length,
            "average_recurrence": avg_recurrence,
            "average_density": avg_density,
            "methods_used": list(methods_used),
            "top_patterns": sorted(self.detected_patterns,
                                 key=lambda p: p['recurrence'],
                                 reverse=True)[:5]
        }


if __name__ == "__main__":
    # Usage example
    print("🔍 Recurrent Pattern Detector (Pₖ-scanner)")
    print("=" * 50)

    # Create example sequence
    example_sequence = "0101001101010011010100110101001101010011"

    detector = PatternDetector(min_pattern_length=3, min_occurrences=2)
    patterns = detector.detect_patterns(example_sequence)

    print(f"Patterns detected: {len(patterns)}")
    for pattern in patterns[:3]:  # Show only first 3
        print(f"  - {pattern['pattern_data']} (occurrences: {pattern['recurrence']})")

    summary = detector.get_pattern_summary()
    print(f"Summary: {summary['total_patterns']} patterns, average length: {summary['average_length']:.1f}")
